"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import py2app
from setuptools import setup

APP = ['REAG.py']
DATA_FILES = ["resources", "resources/REAG-BG.jpg"]
OPTIONS = {
    'iconfile': 'resources/REAM_icon.icns',
    'packages': ['random', 'string', 'smtplib', 'tkinter', 're', 'threading', 'datetime', 'faker', 'csv'],
    'plist': {'CFBundleShortVersionString': '0.3.0.0'}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
