"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RandEmailAlias-mac.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'resources/REAM_icon.icns',
    'packages': ['random', 'string', 'smtplib', 'ssl', 'tkinter', 'pyperclip', 'threading', 'datetime', 'PIL'],
    'plist': {'CFBundleShortVersionString': '0.2.4'}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
