"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RandEmailAlias.py']
DATA_FILES = ['/Users/jake/Documents/REAG-BG.jpg']
OPTIONS = {
    'iconfile': '/Users/jake/Documents/REAM_icon.icns',
    'packages': ['random', 'string', 'smtplib', 'ssl', 'tkinter', 'pyperclip', 'threading', 'datetime', 'PIL']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
